<?php

namespace Database\Seeders;

use App\Models\Industry;
use Illuminate\Database\Seeder;

class IndustryTableSeeder extends Seeder
{

  public function run()
  {
    //DB::table('industries')->delete();
    $industries = array(

      'Accounting',
      'Airlines/Aviation',
      'Alternative Dispute Resolution',
      'Alternative Medicine',
      'Animation',
      'Apparel & Fashion',
      'Architecture & Planning',
      'Arts & Crafts',
      'Automotive',
      'Aviation & Aerospace',
      'Banking',
      'Biotechnology',
      'Broadcast Media',
      'Building Materials',
      'Business Supplies and Equipment',
      'Capital Markets',
      'Chemicals',
      'Civil & Social Organization',
      'Civil Engineering',
      'Commercial Real Estate',
      'Computer & Network Security',
      'Computer Games',
      'Computer Hardware',
      'Computer Networking',
      'Computer Software',
      'Construction',
      'Consumer Electronics',
      'Consumer Goods',
      'Consumer Services',
      'Cosmetics',
      'Dairy',
      'Defense and Space',
      'Design',
      'E-Learning',
      'Education Management',
      'Electrical & Electrical Manufacturing ',
      'Entertainment',
      'Environmental Services',
      'Events Services',
      'Executive Office',
      'Facilities Services ',
      'Farming',
      'Financial Services',
      'Fine Art',
      'Fishery',
      'Food & Beverages',
      'Food Production',
      'Fundraising',
      'Furniture',
      'Gambling & Casinos',
      'Glass, Ceramic & Concrete',
      'Government Administration',
      'Government Relations',
      'Graphic Design',
      'Health, Wellness & Fitness',
      'Higher Education',
      'Hospital & Health Care',
      'Hospitality',
      'Human Resources',
      'Import & Export',
      'Individual  & Family Services',
      'Industrial Automation',
      'Information Services',
      'Insurance',
      'International Affairs',
      'International Trade and Development',
      'Internet',
      'Investment Banking',
      'Investment Management',
      'Judiciary',
      'Law Enforcement',
      'Law Practice',
      'Legal Services',
      'Legislative Office',
      'Leisure, Travel & Tourism',
      'Libraries',
      'Logistics & Supply Chain',
      'Luxury Goods & Jewelry',
      'Machinery',
      'Management Consulting',
      'Maritime',
      'Market Research',
      'Marketing and Advertising ',
      'Mechanical or Industrial Engineering',
      'Media Production',
      'Medical Device',
      'Medical Practice',
      'Mental Health Care',
      'Military',
      'Mining & Metals',
      'Motion Pictures & Film',
      'Museum & Institutions',
      'Music',
      'Nanotechnology',
      'Newspapers ',
      'Non-profit Organization Management',
      'Oil & Energy',
      'Online Media',
      'Outsoucing/Offshoring',
      'Package/Freight Delivery',
      'packaging & Containers',
      'Paper & Forest Products',
      'Performing Arts',
      'Pharmaceuticals',
      'Philanthropy',
      'Plastics',
      'Political Organization',
      'Primary/Secondary Education',
      'Printing',
      'Professional Training & Coaching',
      'Program Development',
      'Public Policy',
      'Public Relations & Communications',
      'Public Safety',
      'Publishing',
      'Railroad Manufacturing',
      'Ranching',
      'Real Estate',
      'Recreation Facilities & Services',
      'Religious institutions',
      'Renewables & Environment',
      'Research',
      'Restaurants',
      'Retail',
      'Security & Investigations',
      'Semiconductors',
      'Shipbuilding',
      'Sporting Goods',
      'Sports',
      'Staffing & Recruiting',
      'Supermarkets',
      'Telecommunications',
      'Textiles',
      'Think Tanks',
      'Tobacco',
      'Transport & Localization',
      'Transport/Trucking/Railroad',
      'Utilities',
      'Veterinary',
      'Warehousing',
      'Wholesale',
      'Wine & Spirits',
      'Wireless',
      'Writing & Editing'
    );
    foreach ($industries as $industry) {
      Industry::create(['industries_name' => $industry]);
    }
  }
}
