<?php

namespace Database\Seeders;

use App\Models\Speciality;
use Illuminate\Database\Seeder;

class SpecialityTableSeeder extends Seeder
{

  public function run()
  {

    $types = array(
      'Inside Sales Rep',
      'Outside Sales Rep',
      'Technical Sales Managers',
      'Account Managers',
      'Regional Sales Managers',
      'Managers, Directors & Executives',
      'Merchandiser',
      'Brand Ambassador',
      'Marketing Assistant',
      'Social Media Marketer',
      'Social Media Marketing Manager',
      'Digital Marketer',
      'Digital Marketing Manager',
      'Marketing Analyst',
      'Advertising Coordinator',
      'Advertising Manager',
      'Brand Manager',
      'Public Relations Manager',
      'Manager, Director & Executive',
      'Call Centre Agent',
      'Customer Service Representative',
      'Multi-lingual Customer Service Representative',
      'Client Account Associate',
      'Client Relations Associate',
      'Client Relations Manager',
      'Call Center Representative',
      'Call Center Supervisor',
      'Call Center Managers',
      'Customer Service Manager',
      'Front Desk Associate',
      'Front Desk Manager',
      'Front Desk Receptionist',
      'Help Desk Associate',
      'Hostess',
      'Retail Associate',
      'Managers, Directors & Executives - Customer Service',
      'Art director',
      'Fashion designer',
      'Interior designer',
      'Graphic designer',
      'Floral designer',
      'Cartoonist',
      'Sculptor',
      'Photographer',
      'Illustrator',
      'Special effects artist',
      'Animator',
      'Videographer',
      'Technical writer',
      'Blog Writer',
      'Screenwriter',
      'Editor',
      'Copywriter',
      'Film editor',
      'Music composer',
      'Choreographer',
      'Actor',
      'Singer',
      'Creative Directors',
      'Cloud Computing Specialists',
      'Computer Network Specialists',
      'Computer Support Specialist',
      'Database Administrators',
      'Information Technology Analysts',
      'Information Security Specialist',
      'Software/Application Developers',
      'Web Developers',
      'Managers, Directors and Executives - IT',
      'Data analyst',
      'Business Analyst',
      'Marketing Analyst',
      'Data Architect',
      'Quantitative Analyst',
      'Statistician',
      'Project Manager - Engineering & Construction',
      'Project Manager - Health Care',
      'Project Manager - Financial Services',
      'Project Manager - Law',
      'Project Manager - Technology ',
      'Line supervisor',
      'Manufacturing Manager',
      'Production Planner',
      'Production Manager',
      'Quality Assurance Specialists',
      'Quality Assurance Managers',
      'Safety Specialists',
      'Safety Managers',
      'Operations Research Analyst',
      'Continuous Improvement Specialist',
      'Continuous Improvement Manager',
      'Operations Manager',
      'Managers, Directors and Executives',
      'Procurement Specialist',
      'Procurement Manager',
      'Logistics Coordinator',
      'Supply Chain Coordinator',
      'Logistics Manager',
      'Transport Manager',
      'Transport Planner',
      'Store Keeper',
      'Warehouse Specialist',
      'Warehouse Manager',
      'Distribution Manager',
      'Routing/Scheduling Specialist',
      'Demand Planner',
      'Supply Chain Analyst',
      'Supply Chain Manager',
      'Managers, Directors & Executives',
      'Quantity Surveyor',
      'Land Surveyor',
      'Construction manager',
      'Architect',
      'Landscape architect',
      'Town planners',
      'Drafting Technician',
      'GIS Specialists',
      'Water Engineer',
      'Environmental Engineer',
      'Civil Engineer',
      'Structural Engineer',
      'Geotechnical Engineer',
      'Construction Manager',
      'Mechanical Engineer - Design',
      'Mechanical Engineer - Installation',
      'Mechanical Engineer - Maintenance',
      'Mechanical Engineer - Building Services',
      'Chemical Engineer',
      'Process Engineer',
      'Petroleum Engineer',
      'Electrical Engineer - Design',
      'Electrical Engineer - Installation',
      'Electrical Engineer - Maintenance',
      'Electrical Engineer - Building Services',
      'Electronic Engineer',
      'Mechatronics Engineer',
      'Automotive Engineer - Design',
      'Automotive Engineer - Maintenance',
      'Aerospace Engineer - Design',
      'Aerospace Engineer - Maintenance',
      'Managers, Directors  and Executives',
      'Analytical chemist',
      'Animal technician',
      'Biomedical engineer',
      'Biomedical scientist',
      'Clinical psychologist',
      'Clinical research associate',
      'Clothing/textile technologist',
      'Colour technologist',
      'Food technologist',
      'Forensic scientist',
      'Medicinal chemist',
      'Metallurgist',
      'Plant breeder/geneticist',
      'Product/process development scientist',
      'Research scientist',
      'Scientific laboratory technician',
      'Teaching laboratory technician',
      'Toxicologist',
      'Water quality scientist',
      'Phlebotomists',
      'Blood Bank Specialists',
      'Chemistry Technician',
      'Hematologist',
      'Microbiologist',
      'Molecular Diagnostics Specialist',
      'Cytologist',
      'Histologist',
      'Pathologist',
      'Lab Manager',
      'Cost Estimator',
      'Forensic Accountant',
      'Real Estate Appraiser',
      'Tax Accountant',
      'Accounting Clerk',
      'Accounts Payable/Receivable Clerk',
      'Accounting Information System Specialist',
      'Actuarial Accountant/Insurance Accountant',
      'Bookkeeping',
      'Budget Analyst',
      'Capital Accountant',
      'Comptroller/Financial Controller',
      'Cost Accountant',
      'Environmental Accountant/Sustainability Measurement',
      'Payroll Accountant',
      'Business Valuation Specialist',
      'Certified Financial Planner',
      'Financial Analyst',
      'Tax Consultant',
      'Business Analyst',
      'Investment Analyst',
      'Internal Auditor',
      'External Auditor',
      'Tax Auditor',
      'Forensic Auditor',
      'Life actuary',
      'General Insurance Actuary',
      'Managers, Directors & CFOs',
      'Bank  Teller',
      'Bank Marketing Representative',
      'Branch Manager',
      'Financial Analyst',
      'Personal Banker',
      'Assistant Branch Manager',
      'Loan Officer',
      'Credit Analyst',
      'Relationship Manager',
      'Bank Manager',
      'Asset Manager',
      'Equities Trader',
      'Fixed Income Analyst',
      'Foreign Exchange Trader',
      'Wealth Manager',
      'Equity Analyst',
      'Investment Banker',
      'Portfolio Manager',
      'Internal Auditors',
      'Audit Managers',
      'Compliance Officers',
      'Managers, Directors & Executives',
      'Administrative assistant',
      'Legal or medical assistant',
      'Executive assistant',
      'Office assistant',
      'Receptionist',
      'Office manager',
      'Cashier',
      'Junior Clerk',
      'Senior Clerk',
      'General Clerk',
      'Dietitian',
      'Sous Chef',
      'Head Chef',
      'Executive Chef',
      'Restaurant Manager',
      'Hotel General Manager',
      'Event Planner',
      'Private Security Contractor',
      'Private Investigator',
      'Compensation &  Benefits Specialists',
      'Training & Development Specialists',
      'Employment, Recruitment & Placement Specialists',
      'Human Resources Information System (HRIS) Analysts',
      'Employee Assistance Plan Specialists',
      'Managers, Directors & Executives - HR',
      'Psychologist',
      'Market researcher',
      'Economist',
      'Sociologist',
      'Anthropologist',
      'Political scientist',
      'Environmental Experts',
      'Monitoring & Evaluation Experts',
      'Agricultural Engineer',
      'Agricultural Food Scientist',
      'Agronomist',
      'Aquatic Ecologist',
      'Arborist',
      'Beekeeper',
      'Botanist',
      'Conservationist',
      'Fisheries Biologist',
      'Forest Health Specialist',
      'Horticulturalist',
      'Plant Biologist',
      'Plant Ecologist',
      'Soil And Plant Scientist',
      'Soil Engineer',
      'Water Conservationist',
      'Water Quality Specialist',
      'Livestock production manager',
      'Animal nutritionist',
      'Veterinarian',
      'Animal scientist',
      'Animal geneticist',
      'Farm manager',
      'Lawyer',
      'Paralegal',
      'Legal Secretary',
      'Legal Assistant',
      'Compliance Specialist',
      'Conflicts Analyst',
      'Litigation Support Professional',
      'E-Discovery Professional',
      'Document Coder',
      'Judge',
      'Magistrate',
      'Law Clerk',
      'Mediator',
      'Forensic Scientist',
      'Legal Videographer',
      'Accident Re-constructionist',
      'Law Firm Administrator',
      'Contract Administrator',
      'Physician (ER doctors, surgeons, hospitalists)',
      'Nurse (CRNA, RN, LPN/LVN, CNS)',
      'Clinical Officers',
      'Techs (Radiology Tech, Ultrasound Tech, Surgical Tech)',
      'Therapist (Physical Therapist, Radiation Therapist)',
      'Medical Assistants',
      'Pharmacists',
      'Medical Technologist & Medical Laboratory Technologist',
      'Dietitian',
      'Patient Attendants',
      'Retail Pharmacist',
      'Clinical Pharmacist',
      'Nuclear Pharmacist.',
      'Home Infusion and Chemotherapist',
      'Administrators,  Managers, Directors & Executives - Healthcare',
    );
    foreach ($types as $type) {
      Speciality::create(['specialities_name' => $type]);
    }
  }
}
